### ISSUE TITLE
Docker Compose Doesn't Work

### ISSUE THREAD

**Issue by only-su** [Lodestone-Team/lodestone#400]
I setup a simple compose script, I aim to expand it to automate a certbot docker to update the lodestone certs. Sadly, trying to start the lodestone service via docker composer always return a rust error
```
lodestone-1  | The application panicked (crashed).
lodestone-1  | Message:  called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
lodestone-1  | Location: core/src/prelude.rs:70
lodestone-1  |
lodestone-1  | Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
lodestone-1  | Run with RUST_BACKTRACE=full to include source snippets.
lodestone-1 exited with code 0
```
I am able to setup a container normally but not via compose for some reason.

Please inform me if I can provide any more help. Thnaks for the awesome work! 

# Steps to reproduce 
Create a file named docker-compose.yml with the following content:
```yaml
services:
  lodestone:
    image: ghcr.io/lodestone-team/lodestone_core
    ports:
      - "16662:16662"
      - "25565:25565"
    restart: unless-stopped
    volumes:
      - ./lodestone_path:/home/user/.lodestone
```
Run `docker compose up` you will get the error.
